version: '3'
services:
  order-service:
    build: ./
    #image: order-service:0.0.5-SNAPSHOT
    environment:
      OTEL_SERVICE_NAME: "order-service"
      OTEL_RESOURCE_ATTRIBUTES: "service=order-service,env=dev"
      OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger:14250"
      # Logs are disabled by default
      OTEL_LOGS_EXPORTER: "otlp"
      OTEL_TRACES_EXPORTER: "jaeger"
    ports:
      - "8080:8080"
    depends_on:
      - jaeger-all-in-one

  jaeger-all-in-one:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: always
    ports:
      - "16686:16686"
      - "14250"

  zipkin-all-in-one:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: opentelemetry
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"